# Generated by Django 3.0.5 on 2020-05-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20200517_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='diaryitem',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
